version: '2'
services:
  mysqldatabase:
     image: mysql:5.7
     networks:            
      network:                
        ipv4_address: 172.25.0.4
     volumes:
      - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_TCP_PORT: 3307
       MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}

     ports:
      - "3308:3307"

  mariadatabase:
     image: mariadb:latest
     networks:            
      network:                
        ipv4_address: 172.25.0.5
     volumes:
      - ./mariadb_data:/var/lib/mysql
     restart: "no"
     environment:
       MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MARIADB_DATABASE}
       MYSQL_USER: ${MARIADB_USER}
       MYSQL_PASSWORD: ${MARIADB_PASSWORD}
       MYSQL_ROOT_HOST: ${MARIADB_ROOT_HOST}

  authentication:
    build: .
    ports:
      - "9000:9000"
    image: "auth:latest"
    networks:            
      network:  

  web:
    build: .
    ports:
      - "2000:2000"
    image: "datawebpage:latest"
    networks:            
      network:  

  resultsweb:
    build: .
    ports:
      - "4002:4002"
    image: "results:latest"
    networks:            
      network:  

  analytics:
    build: .
    ports:
      - "4001:4001"
    image: "analytics:latest"
    networks:            
      network:  

networks:
  network:
    external:
      name: "network1"
  # default:
  #   external:
  #     name: "network1"